baseURL = "https://sergiobelda.dev"
title = "Sergio Belda"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Sergio Belda"
description = "Sergio Belda's personal website"
keywords = [ "Blog", "Android" ]
author = "Sergio Belda"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = ""
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = true
title = "Sergio Belda"
subtitle = "Android Software Engineer"
imageUrl = "images/avatar_2.jpg"
imageWidth = 240
imageHeight = 240
imageTitle = "my image"

[params.homeInfoParams]
Title = "Sergio Belda"
Content = "Android Software Engineer"

[[params.socialIcons]]
name = "github"
url = "https://github.com/serbelga/"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@sergiobelda"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/sergiobelda/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/sergiobeldag/"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[markup.highlight]
noClasses = false
